#!/usr/bin/env bash
# vai_compile_flow.sh — quantize + compile mlp_model.py's TinyMLP for a
# DPU target through the real Vitis AI CLI flow, so it can be deployed and
# timed on the same F1 instance ml_kernel.cpp's HLS kernel targets, for the
# apples-to-apples comparison dpu_vs_custom_model.cpp only estimates.
#
# TODO: requires the Vitis AI Docker image (vai_q_pytorch, vai_c_xir, vart)
# and a DPU overlay bitstream loaded on the F1 card -- neither exists
# locally. Unrun end to end. Each command below is the standard Vitis AI
# 3.x invocation for this flow; failure modes noted inline are anticipated,
# not observed.
set -euo pipefail

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARCH_JSON="${ARCH_JSON:-/opt/vitis_ai/dpu/arch.json}"   # target DPU fingerprint, per-shell
OUT_DIR="${WORKDIR}/compiled"
KERNEL_NAME="mlp_dpu"

mkdir -p "${OUT_DIR}"

# 1. Quantize: calibrate float32 TinyMLP down to the DPU's fixed-point
#    scheme (per-tensor INT8, same bit width as ml_kernel.cpp's ap_int<8>,
#    but the DPU's requantization is table-driven internally rather than
#    the explicit saturate-only step ml_kernel.cpp takes -- see ml_kernel/
#    README.md's note on why that's a real accuracy-relevant difference).
python -m pytorch_nndct.apis quantize \
    --quant_mode calib \
    --model mlp_model.TinyMLP \
    --calib_data mlp_model.calibration_loader \
    --output_dir "${OUT_DIR}/quantize_calib"

python -m pytorch_nndct.apis quantize \
    --quant_mode test \
    --model mlp_model.TinyMLP \
    --calib_data mlp_model.calibration_loader \
    --output_dir "${OUT_DIR}/quantize_result" \
    --deploy

# 2. Compile: lower the quantized XIR graph to a DPU-executable .xmodel
#    targeting the F1 shell's DPU fingerprint (arch.json is generated by
#    the shell build, not authored here -- it encodes PE array size, DDR
#    bank layout, and instruction-set version for this specific overlay).
vai_c_xir \
    -x "${OUT_DIR}/quantize_result/TinyMLP_int.xmodel" \
    -a "${ARCH_JSON}" \
    -o "${OUT_DIR}" \
    -n "${KERNEL_NAME}"

echo "compiled: ${OUT_DIR}/${KERNEL_NAME}.xmodel"
echo "next: vart-based host runner loads this .xmodel onto the DPU and"
echo "times N forward passes the same way pcie_latency/ times ml_kernel.cpp,"
echo "for dpu_vs_custom_model.cpp's estimates to be checked against."
